#!/usr/bin/zsh

# nice ls
eval $(dircolors -b)

# colored man pages
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# di extra filesystem types
export DI_ARGS="-I ext2,ext4,nfs,fuse,tmpfs"

# misc
export PATH="/home/enrico/bin:/home/enrico/apps/bin:/usr/lib/ccache:$PATH"
export LC_COLLATE=C
export LC_TIME=de_DE.utf8

# me
export EMAIL="enrico.troeger@uvena.de"
export NAME="Enrico Tröger"
export FULLNAME="$NAME"

# debian
export DEBEMAIL="$EMAIL"
export DEBFULLNAME="$NAME"

# archlinux
export BUILDDIR=/tmp/makepg

# ignore MC's history stuff
export HISTCONTROL=ignoreboth
export HISTIGNORE=ls:bg:fg:exit:cd:source:.:clear:sudo:su

# grep
export GREP_COLORS="ms=01;38;5;3:mc=01"

# X / GTK
export GTK2_RC_FILES=$HOME/.gtkrc-2.0
export GTK_OVERLAY_SCROLLING=0
export QT_QPA_PLATFORMTHEME=gtk2
export OOO_FORCE_DESKTOP=gnome
export PKG_CONFIG_PATH="/home/enrico/apps/lib/pkgconfig/"
export XDG_DATA_DIRS="/home/enrico/apps/share:/usr/share:$XDG_DATA_DIRS"

# Python
export PYTHONSTARTUP=~/.pythonrc.py
export PYTHONPYCACHEPREFIX=/tmp/__pycache__
export PYTHONBREAKPOINT="web_pdb.set_trace"
export TWINE_USERNAME=eht16

# development
export CFLAGS="-Wall -O2 -pipe -fPIC"
export CXXFLAGS=$CFLAGS
export MAKEFLAGS="-j4"
export NOCONFIGURE=1

# tools
export EDITOR=mcedit
export VISUAL=mcedit
export JOBS=4
