#!/usr/bin/zsh

# basics
alias ..="cd .."
alias cd..="cd .."
alias which='builtin which -a'
alias h='history'
alias ls='ls -h --color=auto --group-directories-first'
alias ll='ls -l -h --color=auto --group-directories-first'
alias la='ls -hal --color=auto --group-directories-first'
alias usb='mount /mnt/usb'
alias usbu='umount /mnt/usb'
alias grep='grep -I -n'
alias make='make -j 2'
alias man='LANG=C man'
alias -g G=' | grep'
alias -g L=' | less'
alias -g S=' | sort'
alias pfkill='pkill -f'
alias pf9kill='pkill -9 -f'
alias wakesrv='wakeonlan 00:11:43:0c:f7:7e'
alias sx='startx'
alias frem='free -m'
alias ifconfig='/sbin/ifconfig'
alias route='/sbin/route'

# debian
alias buildpackage='dpkg-buildpackage -rfakeroot -k700990F2'
alias cleanpackage='fakeroot debian/rules clean'

# misc
alias jap="java -jar /home/enrico/apps/JAP.jar"
alias myip="wget http://privat.uvena.de/myip.php -q -O -"

# geany
alias mg='make && LANG=C ./geany -c /g'
alias wg='waf -j2 && LANG=C _build_/default/geany -c /g'
alias glade='LANG=C glade-2 /home/enrico/projects/geany/geany.glade'

# extensions
alias -s ogg='parole'
alias -s mp3='parole'
alias -s avi='parole'
alias -s py='python'
alias -s pdf='evince'

# without gdb will go into background when running apps
alias tty='stty -tostop'
