#!/usr/bin/zsh

# basics
alias ..="cd .."
alias cd..="cd .."
alias which='builtin which -a'
alias ls='ls -h --color=auto --group-directories-first'
alias ll='ls -l -h --color=auto --group-directories-first'
alias la='ls -hal --color=auto --group-directories-first'
alias pp='ps -ef'
alias less='less -n'  # don't count line numbers
alias usb='mount /mnt/usb'
alias usbu='umount /mnt/usb'
alias grep='grep --color=auto -I -n'
alias make='make -j 2'
alias man='LANG=C man'
alias -g G=' | grep'
alias -g L=' | less'
alias -g S=' | sort'
alias -g J=' | python -mjson.tool'
alias pfkill='pkill -f'
alias pf9kill='pkill -9 -f'
alias frem='free -m'

# debian
alias buildpackage='dpkg-buildpackage -rfakeroot -k579347E6C71A77FA'
alias cleanpackage='fakeroot debian/rules clean'

# GIT
alias gl='git log --graph --pretty=format:"%C(yellow)%h%C(reset) %G? %C(bold blue)%an%C(reset) %s%C(bold cyan)%d%C(reset) %C(green)%cr.%C(reset)"'

# misc
alias myip="echo -n 'IPv4: ' && wget --prefer-family=IPv4 https://v4.mgmt.uvena.de/ip/auto/ -q -O - && echo && echo -n 'IPv6: ' && wget --prefer-family=IPv6 https://v6.mgmt.uvena.de/ip/auto/ -q -O - ; echo"

# geany
alias mg='make && LANG=C src/geany -vc /g'

# without gdb will go into background when running apps
alias tty='stty -tostop'

# virtualenv activate / Django
alias vac="source venv/bin/activate"
alias vpython="venv/bin/python"
alias vpip="venv/bin/pip"

# Docker
alias dc="docker-compose"
alias dr="docker run"
