#!/usr/bin/zsh

# basics
alias ..="cd .."
alias cd..="cd .."
alias which='builtin which -a'
alias h='history'
alias ls='ls -h --color=auto --group-directories-first'
alias ll='ls -l -h --color=auto --group-directories-first'
alias la='ls -hal --color=auto --group-directories-first'
alias less='less -n'  # don't count line numbers
alias grep='grep --color=auto -I -n'
alias make='make -j 2'
alias man='LANG=C man'
alias -g G=' | grep'
alias -g L=' | less'
alias -g S=' | sort'
alias -g J=' | python -mjson.tool'
alias pfkill='pkill -f'
alias pf9kill='pkill -9 -f'
alias frem='free -m'
alias apti='eatmydata aptitude'
alias nss='netstat -tulpen -W'

# JSON pretty print
alias jpp='python -mjson.tool'
