#!/usr/bin/zsh

# nice ls
eval $(dircolors -b)

# colored man pages
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# di extra filesystem types
export DI_ARGS="-I ext2,ext4,nfs,fuse,tmpfs"

# misc
export PATH="/root/bin:$PATH"
export LC_COLLATE=C
export LC_TIME=de_DE.utf8

# me
export EMAIL="enrico.troeger@uvena.de"
export NAME="Enrico Tröger"
export FULLNAME="$NAME"

# debian
export DEBEMAIL="$EMAIL"
export DEBFULLNAME="$NAME"

# ignore MC's history stuff
export HISTCONTROL=ignoreboth
export HISTIGNORE=ls:bg:fg:exit:cd:source:.:clear:sudo:su

# grep
export GREP_COLORS="ms=01;38;5;3:mc=01"

# tools
export EDITOR=mcedit
export VISUAL=mcedit
export JOBS=4
