#!/usr/bin/zsh

# basics
alias ..="cd .."
alias cd..="cd .."
alias which='builtin which -a'
alias h='history'
alias ls='ls -h --color=auto --group-directories-first'
alias ll='ls -l -h --group-directories-first'
alias la='ls -hal --group-directories-first'
alias grep='grep -I -n'
alias make='make -j 2'
alias man='LANG=C man'
alias -g G=' | grep'
alias -g L=' | less'
alias -g S=' | sort'
alias pfkill='pkill -f'
alias pf9kill='pkill -9 -f'
alias wakesrv='wakeonlan 00:11:43:0c:f7:7e'
alias nss='netstat -tulpen -W'
alias apti='eatmydata aptitude'
alias frem='free -m'

