#!/usr/bin/zsh


#enable core dumps
#ulimit -c 1048576

# nice ls
eval $(dircolors -b)

# colored man pages
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'


# misc
export LC_COLLATE=C

# me
export EMAIL="enrico.troeger@uvean.de"
export NAME="Enrico Tröger"
export FULLNAME="$NAME"

# debian
export DEBEMAIL="$EMAIL"
export DEBFULLNAME="$NAME"

# ignore MC's history stuff
export HISTCONTROL=ignoreboth
export HISTIGNORE=ls:bg:fg:exit:cd:source:.:clear:sudo:su

# grep
export GREP_OPTIONS="--color=auto";
export GREP_COLOR="01;38;5;3;"

# tools
export EDITOR=mcedit
export VISUAL=mcedit
export JOBS=2

